name: "Bank-Payments-API-Production"

on:
  workflow_dispatch: # Manual trigger for your demo

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production #Triggers the "production" claim for JFrog
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: hs-gh # Must match JFrog Provider Name
          
          
      - name: Upload Test Artifact
        run: |
          echo "test content" > test-artifact.txt
          # Replace with your project's repository
          jf docker pull hts2-hs-dock-demo-docker.jfrog.io/memcached:bookworm
          jf audit
          jf docker push hts2-hs-dock-demo-docker.jfrog.io/memcached:bookworm
          jf rt bp hs-oidc 1
