name: "Bank-Payments-API-Production"

on:
  workflow_dispatch: # Manual trigger for your demo

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production #Triggers the "production" claim for JFrog
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: hs-gh # Must match JFrog Provider Name

      - name: Verify Connection
        run: |
          echo "Testing connection..."
          jf rt ping
          
      - name: Verify User Identity
        run: |
          echo "Checking who I am authenticated as..."
          jf rt curl -XGET /api/security/users/current
          
      - name: Test Repository Access
        run: |
          echo "Testing access to project repositories..."
          # Replace with a repository in your project
          jf rt curl -XGET /api/repositories/hs-dock-demo-docker-local/
          
      - name: Upload Test Artifact
        run: |
          echo "test content" > test-artifact.txt
          # Replace with your project's repository
          jf rt upload test-artifact.txt hs-dock-demo-docker-local/test/
